const Erros = {
    ID_INVALIDO: 'ID_INVALIDO',
    NOME_VAZIO: "NOME_VAZIO",
    NOME_GRANDE: 'NOME_GRANDE',
    NOME_PEQUENO: 'NOME_PEQUENO',
    NOME_SEM_SOBRENOME: 'NOME_SEM_SOBRENOME',
    NOME_CARACTERES_INVALIDOS: 'NOME_CARACTERES_INVALIDOS',
    CPF_INVALIDO: "CPF_INVALIDO",
    SENHA_INVALIDA: 'SENHA_INVALIDA',
} as const

export default Erros